more consolidated mesh executables and cleanup
SCIInstitute/ShapeWorks pull request #1052
Opened 2021-02-23 19:38 UTC by cchriste

This is new work consolidating various mesh executables. Not sure if any of it needs to go into 6.0, but from here on out we're going to try to keep our branches more specifically named and incremental.

Changes:
- removing default spacing for Image::setSpacing function *
- addition of handy Image::rotate function that simply accepts Axis::X/Y/Z, in addition to more general version *
- removal of GenericMeshConversion util (including VTKUnstructuredGridToPolyData, FeaFromVTK, vtk2ply, stl2vtk, stl2ply, ply2vtk)
- addition of Mesh::clipClosedSurface function *
- removal of unnecessary RasterizationOrigin and RasterizationSize commands (private functions in Mesh)
- fixes and simplifications for clipping in GroomUtils
- misc cleanups and clarifications in Image, Commands, GroomUtils, and Python bindings
- removal of ExtractVertexFeatureFromMesh 
- removal of WriteFeatureGradientAsText
- added notes in code for related GitHub issues (e.g., adding ability to use google test for private functions)

*and associated command line and python bindings

2021-02-23 19:48 UTC, cchriste commented
TODO before this is ready:

**For Mesh::clipClosedSurface, add...**
- [ ]  MeshTest
- [ ]  shapeworksTest
- [ ]  python binding
- [ ]  pythonTest

2021-02-24 11:25 UTC, archanasri approved these changes

2021-02-24 15:47 UTC, akenmorris requested changes
This looks like a lot of great additions!

I'm noticing a lot of inconsistencies in command names with regard to word separation.  For example, I see "readparticlesystem" in some parts of the repo and "read-particle-system" in other parts.

2021-02-24 16:13 UTC, archanasri commented
@akenmorris Our command line interface supports both: read-particle-system and readparticlesystem. All the test cases use without hyphens.

2021-02-24 17:17 UTC, cchriste commented on Applications/shapeworks/MeshCommands.cpp
> +  bool allowbackintersections = static_cast<bool>(options.get("allowbackintersections"));
I updated all the variables in the commands to use camelCase, keeping the arguments themselves all lowercase.

2021-02-24 17:24 UTC, cchriste commented
@akenmorris if you feel this is complete please go ahead and merge and delete the branch. Let us party no more.

2021-02-24 18:13 UTC, akenmorris approved these changes

2021-02-24 18:25 UTC, akenmorris commented
Thanks for updating the C++ variable names.

Regarding the command line interface, I'll just comment that I disagree with multi-word options using all lowercase and no word separation (e.g. --allowbackintersections).  That one is probably fairly readable, but I can anticipate problems with this approach in the future.  If this is ok with you, @sheryjoe , then let's go ahead and I will keep quiet.  I just thought we had decided to use dashes at a meeting a while back.  Was this decision reversed and I just missed it?

I'm just looking at other command line interfaces I commonly use (e.g. c3d, ImageMagick, `man ls`, `git help`, `gcc --help`), and they all use dashes.  I'm not seeing examples of multi-word options with no word separation.  Can I ask what the rational is for this approach?

2021-02-24 18:45 UTC, sheryjoe commented
> Regarding the command line interface, I'll just comment that I disagree with multi-word options using all lowercase and no word separation (e.g. --allowbackintersections). 

I agree with @akenmorris. We have discussed this before in the context of subcommand names when we started the consolidation work to make sure that subcommands are readable without having to remember CamelCased composite words. The consensus was that we will use multi-word commands with dashes/hyphens for word separation with the option of no-dashes for developer(s) convenience.  Commands arguments/options are no different here.

2021-02-24 22:46 UTC, cchriste commented
> I agree with @akenmorris. We have discussed this before in the context of subcommand names when we started the consolidation work to make sure that subcommands are readable without having to remember CamelCased composite words. The consensus was that we will use multi-word commands with dashes/hyphens for word separation with the option of no-dashes for developer(s) convenience. Commands arguments/options are no different here.

Great! I just created #1056 to change all of them. If possible, let's merge this PR and address that separately since it's a broader issue requiring updating of all examples as well as the commands themselves.

2021-02-25 01:54 UTC, merged