Documentation and small fixes
SCIInstitute/ShapeWorks pull request #1344
Opened 2021-06-23 17:47 UTC by jadie1

This PR includes documentation fixes and updates.

And various small fixes from Cameron in lieu of PR #1339:
- add a blurb about starting the notebook server to the notebooks page in docs
- update notebooks page to show the copied notebooks in docs/notebooks
- note: did not update videos or notebooks themselves
- minor updates and clarification to data augmentation notebook
- add docs for using git-bash on windows
- remove Testing/data/simple/simple.xml since it's never used

To test, checkout the fix_docs branch and from the main ShapeWorks dir run: `mkdocs serve`
Check that documentation looks complete and correct.

2021-06-23 18:07 UTC, cchriste commented on docs/use-cases/ellipsoid-multiple-domain-mesh.md
> +ShapeWorksStudio visualizes/analyzes the optimized particle-based shape model by visualizing the mean shape, individual shape samples, and the shape modes of variations. For more information, see: [H
ShapeWorks Studio

2021-06-23 18:08 UTC, cchriste commented on docs/new/new-studio.md
> +As of ShapeWorks 6.0, we added mesh support to ShapeWorks Studio including loading meshes, optimizing shape models directly on meshes, and visualizing meshes with scalar feature values. Meshes can st
ShapeWorks Studio (the second time it appears on the line)

2021-06-23 18:08 UTC, cchriste commented on docs/use-cases/ellipsoid-multiple-domain-mesh.md
> +* Launches ShapeWorksStudio to visualize the use case results (i.e., the optimized shape model and the groomed data) by calling functions in `AnalyzeUtils.py` (in `Examples/Python/`).
ShapeWorks Studio?

2021-06-23 18:14 UTC, cchriste requested changes
This is a lot to review, so one concrete item: ShapeWorksStudio is sometimes replaced with ShapeWorks Studio, but other times it hasn't been replaced and doesn't seem to be referring to the command. Likely these should be consistent throughout. 

In general, there are lots and lots of cut-and-pasted pages or subsections thereof in here. Is it possible there is a better way to organize these use case descriptions? I realize they may not all be identical, but if a user has gone through a couple of them they'll be skimming the things they've read before anyway and very likely miss any differences. Instead, a shared section might summarize and each use case description note any differences.

2021-06-23 19:41 UTC, archanasri commented on docs/new/ellipsoid-joint-generation.md
> +`ShapeCohortGenerator` is a python package that generates synthetic shape cohorts with groundtruth surface correspondences by varying different parameters describing such shape families.
ground truth*

2021-06-23 19:42 UTC, archanasri commented on docs/new/ellipsoid-joint-generation.md
> +The [notebook](../notebooks/getting-started-with-shape-cohort-generation.html) will soon be updates with examples of ellipsoid joint generation
updated*

2021-06-23 19:50 UTC, archanasri commented on docs/use-cases/femur.md
> +9. **Cropping**: The images and segmentations are cropped so that all of the samples are within the same bounding box. The bounding box parameters are computed based on the smalles bounding box that
smallest*

2021-06-23 20:03 UTC, archanasri commented on docs/use-cases/femur-cutting-planes.md
> +We start with full unsegmented images (CT scans) of each femur's hip and segmented meshes in this use case. ShapeWorks needs a volumetric representation of shapes in the form of signed distance trans
(i.e., binary segmentations). Additionally,*

2021-06-23 20:05 UTC, archanasri commented on docs/use-cases/thin-cavity-bean.md
> +$ python RunUseCase.py --use_case thin_cavity_bean
$ python RunUseCase.py thin_cavity_bean

2021-06-23 20:06 UTC, archanasri commented on docs/use-cases/supershapes-contour.md
> +$ python RunUseCase.py --use_case supershapes_1mode_contour
$ python RunUseCase.py supershapes_1mode_contour

2021-06-23 20:09 UTC, archanasri commented on docs/use-cases/ellipsoid-pca.md
> +$python RunUseCase.py --use_case ellipsoid_pca
$ python RunUseCase.py ellipsoid_pca

2021-06-23 20:10 UTC, cchriste approved these changes
I corrected the ShapeWorks Studio inconsistencies and created issue #1347 about improving the organization.

2021-06-23 20:10 UTC, archanasri commented on docs/use-cases/ellipsoid-pca.md
> +The `ParticleShapeStatistics() ` of `ShapeWorks` python API analyzes the optimized particle-based shape model by calculating the principal components of the shape model, eigenvalues, eigenvectors, an
`ParticleShapeStatistics()`

2021-06-23 20:10 UTC, archanasri commented on docs/use-cases/ellipsoid-multiple-domain.md
> +$ python RunUseCase.py --use_case ellipsoid_multiple_domain
$ python RunUseCase.py ellipsoid_multiple_domain

2021-06-23 20:11 UTC, archanasri commented on docs/use-cases/ellipsoid-multiple-domain.md
> +$ python RunUseCase.py --use_case ellipsoid_multiple_domain
$ python RunUseCase.py ellipsoid_multiple_domain

2021-06-23 20:13 UTC, cchriste commented
@sheryjoe Can we take advantage if Christine Pickett for improving and editing our documentation?

2021-06-23 20:13 UTC, archanasri commented on docs/use-cases/ellipsoid-multiple-domain-mesh.md
> +$ python RunUseCase.py --use_case ellipsoid_multiple_domain_mesh
$ python RunUseCase.py ellipsoid_multiple_domain_mesh

2021-06-23 20:14 UTC, archanasri commented on docs/use-cases/ellipsoid-multiple-domain-mesh.md
> +$ python RunUseCase.py --use_case ellipsoid_multiple_domain_mesh
$ python RunUseCase.py ellipsoid_multiple_domain_mesh

2021-06-23 20:37 UTC, archanasri approved these changes

2021-06-23 21:44 UTC, merged

2021-06-24 23:08 UTC, sheryjoe commented
> @sheryjoe Can we get help from Christine Pickett, the SCI Editor, for improving and editing our documentation?

Yes we can. We will need to demonstrate to her how she could edit docs md files on github.