Modes of Variation Doc
SCIInstitute/ShapeWorks pull request #1453
Opened 2021-09-06 23:38 UTC by jadie1

Added to the "What is Shape Modeling?" section of `/docs/getting-started/shapes.md` for issue #990

2021-09-07 15:56 UTC, sheryjoe requested changes
@jadie1 Images are not visible.

2021-09-07 15:56 UTC, sheryjoe commented on docs/getting-started/shapes.md
>  Let’s first consider parameterized geometric shapes. For example, disregarding location, orientiation, and global scale, an ellipse can be fully described by its major and minor radii. A torus can be
typo: it s -> its

2021-09-07 17:23 UTC, jadie1 commented
> @jadie1 Images are not visible.

They are visible for me when I run `mkdocs serve` on this branch. Are the images and videos visible for you in the rest of the documentation?

2021-09-07 18:21 UTC, jadie1 commented
@sheryjoe It seems videos on the SCI server do not show up in the documentation on github (see /docs/use-cases/ellipsoid-cutting-planes.md for another example). But they are there if you run `mkdocs serve`

2021-09-08 06:18 UTC, akenmorris approved these changes

2021-09-08 06:19 UTC, merged