Mesh distance symmetric
SCIInstitute/ShapeWorks pull request #2041
Opened 2023-04-05 13:49 UTC by nawazishkhan1-nk

[WIP] - Do Not Merge

## Summary
This PR addresses issue #2040.

## Changes Made
- Non-breaking change: Added a new distance method in Mesh class to compute symmetric point-to-cell distances.
- Included this method in the ShapeWorks Python API.
- Temporarily called it in ShapeWorks Studio Viewer.

## Testing Done
- Tested the new distance method using different meshes.
- Checked that the ShapeWorks Studio Viewer and API calls run without errors.

## Known Issues
- None at this time.

## Screenshots
- None.

2023-04-21 03:26 UTC, akenmorris requested changes
Looks good, just a couple minor things.

2023-04-21 03:26 UTC, akenmorris commented on Studio/Visualization/Viewer.cpp
> +        std::cout << "Debug Mode | Computing distance with SymmetricPointToCell method in Studio Viewer " << std::endl;
K, let's remove this debug line and I think it's good to go.

2023-04-21 03:26 UTC, akenmorris commented on Libs/Mesh/Mesh.cpp
> +      auto targetCellLocator = vtkSmartPointer<vtkCellLocator>::New();
use the faster vtkStaticCellLocator

2023-04-21 03:26 UTC, akenmorris commented on Libs/Mesh/Mesh.cpp
> +      auto refCellLocator = vtkSmartPointer<vtkCellLocator>::New();
vtkStaticCellLocator as above

2023-04-26 20:53 UTC, ben2k commented
> [WIP] - Do Not Merge
> 
> ## Summary
> This PR addresses issue #2040.
> 
> ## Changes Made
> * Non-breaking change: Added a new distance method in Mesh class to compute symmetric point-to-cell distances.
> * Included this method in the ShapeWorks Python API.
> * Temporarily called it in ShapeWorks Studio Viewer when surface-to-surface distance is checked.
> 
> ## Testing Done
> * Tested the new distance method using different meshes.
> * Checked that the ShapeWorks Studio Viewer and API calls run without errors.
> 
> ## Known Issues
> * None at this time.
> 
> ## Screenshots
> Symmetric Point-to-cell distance vs. regular Point-to-cell distance <img alt="Screen Shot 2023-04-05 at 8 28 20 AM" width="1134" src="https://user-images.githubusercontent.com/84894476/230112329-c9f52abb-3032-4050-aee1-10994f821c31.png">

Hello, I propose also to add the signed point-to-cell metric, I will amend the commit

2023-04-26 20:54 UTC, ben2k commented
Hello, I propose also to add the signed point-to-cell metric, I will amend the commit

2023-04-26 21:43 UTC, ben2k commented on Libs/Mesh/Mesh.cpp
> +    case SymmetricPointToCell: {
Missing a unit test for that case ?

2023-06-27 23:03 UTC, akenmorris commented
@nawazishkhan1-nk , do you have an update on the PR?

2023-10-25 15:01 UTC, akenmorris commented
@nawazishkhan1-nk , any update on this?

2024-08-27 21:19 UTC, ben2k commented
> Hello, I propose also to add the signed point-to-cell metric, I will amend the commit

I don't have the time but I suggest we add the signed  point-to-cell metric: the sign is defined as follow:

// Determine the signed distance
const Vector normal = in_transfo * in_normals[i]; // get the normal of source mesh for vertex i
const Vector v = closest_point_ref_i - point[i]; // get the vector between the closest point in the reference and the vertex i 
signed_distance = sign( dot(v, normal) ) * norm(closest_point_ref_i - point[i]);

2024-08-27 21:21 UTC, ben2k commented
Additionally, instead of this symmetric distance (that will never be higher than traditional point-to-cell metric), I would propose that we implement the Chamfer Distance (sum of A to B and B to A distances) which is used in numerous publications to compare mesh to mesh.

2024-08-28 22:25 UTC, akenmorris commented
> Additionally, instead of this symmetric distance (that will never be higher than traditional point-to-cell metric), I would propose that we implement the Chamfer Distance (sum of A to B and B to A distances) which is used in numerous publications to compare mesh to mesh.

The Chamfer Distance, as far as I can find, is only defined for point sets. Do you propose to use vertices only and not the point to cell distance?

2026-08-12 13:57 UTC, akenmorris commented
Closing PR for now, re-open when ready.

2026-08-12 13:57 UTC, closed without merging