Use case arguments
SCIInstitute/ShapeWorks pull request #784
Opened 2020-10-16 20:37 UTC by jadie1

To address issue #760 I made the following changes:

- Changed `--start_with_prepped_data` to `--skip_grooming`
- Changed `--start_with_image_and_segmentation_data` to `--groom_images`
- Updated RunUseCases.py to print a warning if  `--groom_images` is used with a use case that does not have images.
- Updated the use case documentation for these changes on the mkdocs branch. 

To test run the use cases with these new tags.

2020-10-19 15:03 UTC, sheryjoe requested changes

2020-10-19 15:03 UTC, sheryjoe commented on Examples/Python/femur.py
> +    if args.skip_grooming:
If getting the distance transforms file list is the same for all use cases, it is worth modularizing it into a utils function. For example, get_file_list with arguments directory, extension, is_tiny_test, num_samples.

2020-10-19 15:03 UTC, sheryjoe commented on Examples/Python/femur_cut.py
> +    if args.skip_grooming:
same comment about a function for file list.

2020-10-19 15:03 UTC, sheryjoe commented on Examples/Python/left_atrium.py
> +    if args.skip_grooming:
Same here.

2020-10-19 20:19 UTC, jadie1 commented on Examples/Python/RunUseCase.py
> +if args.groom_images and args.use_case.lower() not in image_use_cases:
Agreed

2020-10-23 01:04 UTC, jadie1 commented
I made a common function for getting prepped data and addressed all of your comments @sheryjoe
I updated the documentation on the makedocs branch and tested all the use cases.

2020-10-23 13:49 UTC, sheryjoe requested changes
get_data (which downloads data) and get_groomed_data (which retrieves the file list in a directory) in CommonUtils do not have function names that reflect their functionality and it seems confusing.

2020-10-26 02:36 UTC, jadie1 commented
I changed "get_data" to "download_and_unzip_dataset" and I changed "get_groomed_data" to "get_distance_transform_list". Let me know if you can think of a better name for these functions.

2020-10-26 19:52 UTC, sheryjoe commented
@jadie1 I don't think that get_distance_transform_list has anything specific to distance transforms. I would make this as a general get_file_list function with arguments for the extension to search for and the path to search in.

2020-10-27 13:56 UTC, sheryjoe approved these changes

2020-10-27 14:49 UTC, akenmorris approved these changes
Looks good.

2020-10-27 14:49 UTC, merged