Studio mesh reconstruction
SCIInstitute/ShapeWorks pull request #915
Opened 2021-01-25 20:42 UTC by akenmorris

This PR addresses the following issues:

	• #914 - Mesh and particles disappear in studio after optimization
	• #913 - Studio: automatic glyph size 
	• #911 - Studio: Allow choice of surface reconstruction method based on data
	• #902 - Studio: optimize tool should load images in the worker thread
	• #822 - Studio should auto-run the surface reconstruction like View2 does
	• #870 - Studio: Drag and Drop image volumes and meshes to import 
	• #844 - Mesh reconstruction via template transform to studio for mesh support

2021-01-26 18:54 UTC, medakk commented
This is great stuff!! :D 


I noticed this weird behaviour: after optimizing, if I go to analyze, it seems to be using mesh-warping based reconstruction but the radio button says its using legacy:
![image](https://user-images.githubusercontent.com/10536745/105890912-31995980-5fcd-11eb-984d-02a60e132d54.png)

2021-01-26 23:41 UTC, akenmorris commented
@medakk , yes indeed.  Will push fixes shortly.

2021-01-28 01:23 UTC, cchriste commented on Libs/Mesh/Mesh.h
> +  // Mesh(vtkSmartPointer<vtkPolyData>&& rhs) : mesh(std::move(rhs)) {}
Please see my comments about this in the mesh warp pull request.

2021-01-28 01:28 UTC, cchriste requested changes
Looks mostly okay. Just the pieces from the mesh warp pull request (modifications to Mesh constructors and assignment operators, etc., just see the comments over there). Otherwise, great.

I suggest merging it with the new alpha branch, thus enabling testing the consolidated mesh work from three branches before springing it on an unsuspecting master branch.

2021-02-01 16:03 UTC, closed without merging